package com.arams.beans;
// Generated Apr 8, 2020, 8:15:09 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductImageId generated by hbm2java
 */
@Embeddable
public class ProductImageId  implements java.io.Serializable {


     private int productId;
     private String url;

    public ProductImageId() {
    }

    public ProductImageId(int productId, String url) {
       this.productId = productId;
       this.url = url;
    }
   


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


    @Column(name="url", nullable=false, length=45)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProductImageId) ) return false;
		 ProductImageId castOther = ( ProductImageId ) other; 
         
		 return (this.getProductId()==castOther.getProductId())
 && ( (this.getUrl()==castOther.getUrl()) || ( this.getUrl()!=null && castOther.getUrl()!=null && this.getUrl().equals(castOther.getUrl()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProductId();
         result = 37 * result + ( getUrl() == null ? 0 : this.getUrl().hashCode() );
         return result;
   }   


}


