package com.arams.beans;
// Generated Apr 8, 2020, 8:15:09 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductImage generated by hbm2java
 */
@Entity
@Table(name="product_image"
    ,catalog="ecommerce"
)
public class ProductImage  implements java.io.Serializable {


     private ProductImageId id;

     @JsonBackReference
     private Product product;

     private int quantity;

    public ProductImage() {
    }

    public ProductImage(ProductImageId id, Product product, int quantity) {
       this.id = id;
       this.product = product;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="productId", column=@Column(name="product_id", nullable=false) ), 
        @AttributeOverride(name="url", column=@Column(name="url", nullable=false, length=45) ) } )
    public ProductImageId getId() {
        return this.id;
    }
    
    public void setId(ProductImageId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="product_id", nullable=false, insertable=false, updatable=false)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }

    
    @Column(name="quantity", nullable=false)
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


